version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda
  create_env: &create_env
    run:
      name: create env
      command: |
        conda create -n kipoi-dev python=3.6
  install_git_lfs: &install_git_lfs
    run:
      name: Install git-lfs
      command: |
        source activate kipoi-dev
        conda install --yes -c conda-forge git-lfs
        cp .circleci/gitconfig ~/.gitconfig
  update_pytorch: &update_pytorch
    run:
      name: Update pytorch
      command: |
        source activate kipoi-dev
        conda install --yes pytorch-cpu -c pytorch
  icondaall_pip_deps: &install_pip_deps
    run:
      name: Install pip dependencies
      command: |
        source activate kipoi-dev
        pip install genomelake --no-deps
        pip install pyfaidx
  install_conda_deps: &install_conda_deps
    run:
      name: Install conda dependencies
      command: |
        source activate kipoi-dev
        conda install -c bioconda cyvcf2 pybedtools genomelake pyfaidx 
  install_kipoi: &install_kipoi
    run:
      name: Install Kipoi
      command: |
        source activate kipoi-dev
        git clone git@github.com:kipoi/kipoi.git kipoi_pkg
        cd kipoi_pkg
        pip install '.'
        cd ..
  install_kipoiseq: &install_kipoiseq
    run:
      name: Install kipoiseq
      command: |
        source activate kipoi-dev
        pip install '.[develop]'
  install_requests: &install_requests
    run:
      name: Install requirements for requests correctly
      command: |
        source activate kipoi-dev
        pip install requests
  kipoi_ls: &kipoi_ls
    run:
      name: List kipoi packages
      command: |
        source activate kipoi-dev
        kipoi ls
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        source activate kipoi-dev
        mkdir test-reports
        py.test --cov=kipoiseq/ tests/ -n 1 --no-cov-on-fail --junitxml=test-reports/junit.xml
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: |
          source activate kipoi-dev
          coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports


jobs:

  test-py36:
    docker:
      - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *create_env
      - *update_pytorch
      - *install_conda_deps
      - *install_kipoi
      - *install_kipoiseq
      - *kipoi_ls
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts



  build-deploy-docs:
    docker:
      - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - e3:44:16:ec:72:df:ae:59:82:c2:ee:57:4a:52:71:aa
      - checkout
      - *update_conda
      - *create_env
      - *install_conda_deps
      - *install_kipoi
      - *install_kipoiseq
      - run:
          name: Install build deps
          command: |
            source activate kipoi-dev
            pip install nbconvert mkdocs git+https://github.com/kipoi/pydoc-markdown@master
      - run:
          name: Build docs
          command: |
            source activate kipoi-dev
            cd docs/
            mkdir -p theme_dir/img/ipynb/
            ./render_ipynb.bash
            pydocmd build
      - run:
          name: Deploy docs
          command: |
            source activate kipoi-dev
            .circleci/deploy_docs.bash

workflows:
  version: 2
  test:
    jobs:
      - test-py36
      - build-deploy-docs:
          requires:
            - test-py36
          filters:
            branches:
              only:
                - master
                - test_deployment_script
